[package]
name = "ladon-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
unicode-normalization.workspace = true
uuid.workspace = true
minicbor.workspace = true
zeroize.workspace = true

[dev-dependencies]
serde = "1"
static_assertions = "1"
